regen-network/regen-ledger

- .codecov.yml
- .gitignore
- .gitlab-ci.yml
- Makefile
- tests/test_cover.sh
- x/esp/esp_test.go
> [#9] add codecov coverage reporting

- CHANGELOG.md
- x/schema/client/cli/query.go
- x/schema/client/cli/tx.go
- x/schema/client/module_client.go
- x/schema/client/rest/rest.go
- x/schema/codec.go
- x/schema/doc.go
- x/schema/handler.go
- x/schema/keeper.go
- x/schema/msgs.go
- x/schema/schema_test.go
- x/schema/types.go
> #17 add property schema support

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/CODEOWNERS.md
[Closes #6 ]
- link to Stories on Board/Zenhub, describe methodology - i.e. story mapping, agile/pull methodology
- link to Gitter channel
- describe documentation & testing workflows
- describe working group/design workflows
- configure Github PR reviewers/CODEOWNERS and issue templates
- mention "help wanted" and "good first issue" labels and mark some issues as such
- add code of conduct
> #6 contributing

- cmd/xrncli/main.go
- types/types.go
- util/test.go
- x/claim/claim_test.go
- x/claim/client/cli/query.go
- x/claim/client/cli/tx.go
- x/claim/client/module_client.go
- x/claim/codec.go
- x/claim/handler.go
- x/claim/keeper.go
- x/claim/msgs.go
- x/data/data_test.go
- x/data/keeper.go
- x/schema/schema_test.go
- x/schema/test/helpers.go
> #27 Create claim module

- .gitlab-ci.yml
- app/app.go
> Change PowerReduction from 1 million to 1 hundred for testnet

- CONTRIBUTING.md
I added in a poem, and more importantly, this is the first time I have ever made a pull request (besides the one I did on gitlab 20 minutes ago before clare informed me that we don't use that any more. 
Let me know if it looks like I did this right!
> Update CONTRIBUTING.md with Maya Angelou

- app/app.go
Fixes #
-
-
-
Feel free to submit a Draft Pull Request as soon as you start working on something. Before you mark your PR as Ready For Review, make sure you've checked off the following boxes or indicated N/A (not applicable):
Thanks!
> Patagonia proposal

- app/app.go
Fixes #
-
-
-
Feel free to submit a Draft Pull Request as soon as you start working on something. Before you mark your PR as Ready For Review, make sure you've checked off the following boxes or indicated N/A (not applicable):
Thanks!
> Added handler for papua upgrade

- docs/.vuepress/config.js
Github link on regen ledger docs was broken.
> Update github link on docs

- proto/regen/data/v1alpha1/events.proto
- proto/regen/data/v1alpha1/genesis.proto
- proto/regen/data/v1alpha1/query.proto
- proto/regen/data/v1alpha1/tx.proto
- proto/regen/ecocredit/v1alpha1/events.proto
- proto/regen/ecocredit/v1alpha1/query.proto
- proto/regen/ecocredit/v1alpha1/tx.proto
- proto/regen/ecocredit/v1alpha1/types.proto
- testutil/testdata/codec.proto
I've edited a protobuf files and then run formater. It created many changes and decided to ship it in a separate PR.
> format proto files

- app/experimental_appconfig.go
- Add `Mau` upgrade handler for testnet phase-3
> Add upgrade handler

- app/addr_prefixes.go
- docs/api.md
> Remove colon from regen addresses

- app/app.go
- app/experimental_appconfig.go
- app/stable_appconfig.go
- app/wasm_wrapper.go
> Move cosmwasm into experimental build

- x/group/client/tx.go
Fix typo in `update-group-metadata` command
> update group tx commands

- .codecov.yml
- .github/workflows/test.yml
- .gitignore
- Makefile
- app/experimental_appconfig.go
- app/stable_appconfig.go
- scripts/test_cover.sh
> ci: codecov for all modules

- app/stable_appconfig.go
Sorry, I forgot to update this in #403 
---
I have...
I have...
> fix: Fix upgrade name causing panic on migrations

- x/ecocredit/client/tx.go
small logic error in `ecocredit/client/tx.go` where its returning a nil error
Closes: n/a
---
I have...
I have...
> fix: logic error in ecocredit

- x/ecocredit/genesis_test.go
- x/ecocredit/params.go
- x/ecocredit/params_test.go
- x/ecocredit/server/testsuite/suite.go
This pull request updates the unit value within the default credit type to be more descriptive.
---
I have...
I have...
> fix: more descriptive carbon unit

- x/ecocredit/client/testsuite/tx.go
- x/ecocredit/client/util.go
- x/ecocredit/denom.go
- x/ecocredit/errors.go
- x/ecocredit/params.go
- x/ecocredit/server/credit_type.go
- x/ecocredit/server/msg_server.go
Closes: #499 
ref: #502 
---
I have...
I have...
> fix: fix `create-class` to return proper errors

- app/export.go
Closes: #523 
---
I have...
I have...
> chore: fix state export for zero height

- x/ecocredit/client/query.go
- x/ecocredit/client/tx.go
- x/ecocredit/client/util.go
- x/ecocredit/denom.go
- x/ecocredit/expected_keepers.go
- x/ecocredit/module/module.go
- x/ecocredit/msgs.go
- x/ecocredit/params.go
- x/ecocredit/server/query_server.go
- x/ecocredit/types.go
Ref: #350
Add missing comments for improved inline godoc experience.
---
I have...
I have...
> chore: add missing comments

- go.mod
- go.sum
- orm/go.mod
- orm/go.sum
- types/go.mod
- types/go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/group/go.mod
- x/group/go.sum
Previously, the go.mod replace directive for our SDK fork's tag was set to `v0.44.0-regen-1`. When looking at the cached version of this tag at proxy.golang.org ([see here](https://proxy.golang.org/github.com/regen-network/cosmos-sdk/@v/v0.44.0-regen-1.info)), I noticed that it was referencing an older commit which was different from the one referenced on github's tag of `v0.44.0-regen-1`.
The tag on GitHub is the correct tag that the dependency should be tracking, but since proxy.golang.org doesn't support cache invalidation, I pushed a new tag instead (`v0.44.0-regen-2`) and linked Regen-ledger's dependency against this updated tag.
---
I have... …
> fix: update sdk fork to v0.44.0-regen-2

- x/ecocredit/client/query.go
- x/ecocredit/client/testsuite/grpc.go
- x/ecocredit/client/testsuite/query.go
Closes: #553 
---
I have...
I have...
> feat: add ecocredit params query

- x/ecocredit/simulation/operations.go
Closes: #556 
---
I have...
I have...
> feat: add simulations for update credit class messages

- CHANGELOG.md
- RELEASE_NOTES.md
This PR updates changelog & adds release notes for v2.0.0-rc1.
After PR is merged the following actions should take place:
**Note:** Whatever ends up being the last RC will have one final commit after it that tags versions of all the necessary submodules, along with final publishing of the v2.0.0 release.
---
I have...
I have...
> chore: Changelog + Release Notes for v2.0.0-rc1

- docs/migrations/v2.0-upgrade.md
Closes: #611
Update and fix v2.0 migration documentation.
---
I have...
I have...
> docs: update v2.0 migration

- docs/getting-started/README.md
- docs/getting-started/live-networks.md
- docs/getting-started/running-a-full-node.md
- docs/getting-started/running-a-validator.md
- docs/intro/README.md
- docs/migrations/v2.0-upgrade.md
- docs/regen-ledger/README.md
- docs/regen-ledger/interfaces.md
Closes: #566
This pull request includes general updates to the documentation to reflect the latest information.
- Update getting started to use v2.0
- #566
- Add node configuration instructions
- Update core content to reflect v2.0
- Update v2.0 migration documentation
- Add Redwood block height
- Update cosmovisor warning
---
I have...
I have...
> docs: v2.0 content updates

- CHANGELOG.md
- RELEASE_NOTES.md
- app/app.go
> fix: set v2.1.0 upgrade height, update changelog + release notes

- x/data/client/query.go
- x/data/client/testsuite/query.go
- x/data/client/util.go
Closes: #672
This pull request updates the data CLI query commands to reflect the latest changes to the proto API and query server.
---
I have...
I have...
> feat(x/data): update data query commands

- docs/intro/README.md
Add Big Dipper to [list of explorers](https://docs.regen.network/intro/#block-explorers).
---
I have...
I have...
> docs: add big dipper to explorers

- go.mod
- go.sum
- proto/regen/ecocredit/v1alpha1/events.proto
- proto/regen/ecocredit/v1alpha1/genesis.proto
- proto/regen/ecocredit/v1alpha1/query.proto
- proto/regen/ecocredit/v1alpha1/tx.proto
- proto/regen/ecocredit/v1alpha1/types.proto
In #608 we bumped the proto version for the ecocredit module. This pull request reinstates v1alpha1 based on the proto files that were included in the v2.0 release.
---
I have...
I have...
> chore: reinstate ecocredit v1alpha1

- proto/buf.gen.pulsar.yaml
fixes our repo name in our buf pulsar yaml file
Closes: n/a
---
I have...
I have...
> fix: incorrect github name in buf pulsar yaml

- docs/getting-started/live-networks.md
- docs/getting-started/prerequisites.md
- docs/getting-started/running-a-full-node.md
- docs/getting-started/running-a-validator.md
Update mainnet node address throughout documentation.
---
I have...
I have...
> docs: update mainnet node address

- x/ecocredit/basket/msg_take.go
- x/ecocredit/basket/msg_take_test.go
- x/ecocredit/location.go
- x/ecocredit/location_test.go
- x/ecocredit/msgs.go
Ref: #732
---
I have...
I have...
> feat(x/ecocredit): sdk.Msg for MsgTake

- proto/regen/ecocredit/basket/v1/tx.proto
Closes: #XXXX
---
I have...
I have...
> docs(x/ecocredit): clarify basket exponent usage to eliminate rounding

- x/ecocredit/server/basket/query_baskets.go
- x/ecocredit/server/basket/query_baskets_test.go
- x/ecocredit/server/basket/query_util.go
Closes: #XXXX
---
I have...
I have...
> feat(x/ecocredit): query baskets

- x/ecocredit/client/basket/tx.go
Closes: #XXXX
---
I have...
I have...
> chore: fix create-basket cli

- proto/regen/ecocredit/basket/v1/tx.proto
- types/go.mod
- types/math/dec_test.go
- x/ecocredit/server/basket/put.go
- x/ecocredit/server/basket/put_test.go
ref: https://github.com/regen-network/regen-ledger/issues/732
`MsgPut` audit as per https://hackmd.io/IZittJ8fRoOf-defmaloWQ
---
I have...
I have...
> chore(basket): Audit MsgPut

- go.mod
- types/go.sum
- types/math/dec.go
- types/math/dec_test.go
- types/math/testing.go
+ updated tests
+ added math gomock matcher
---
I have...
I have...
> feat(math): backport NewDecFinite and add matcher

- app/app.go
- app/regen/cmd/cmd_test.go
- app/regen/cmd/root.go
- app/regen/main.go
- app/testsuite/network_config.go
- app/testsuite/network_test.go
- go.mod
- x/group/go.mod
Update go.mod to v3 and use latest ecoecredit version.
---
I have...
I have...
> chore: v3 version bump

- .github/workflows/lint.yml
- Makefile
- x/ecocredit/server/msg_server.go
Closes: #807
---
I have...
I have...
> fix: event receive attributes

- CHANGELOG.md
🎉  Closes: #732 
---
I have...
I have...
> chore: changelog updates for v3.0 final

- x/ecocredit/testing/basket/create.feature
- x/ecocredit/testing/basket/put.feature
- x/ecocredit/testing/basket/take.feature
Ref: #732
Add acceptance tests for basket create, put, and take.
---
I have...
I have...
> docs(x/ecocredit): basket acceptance tests

- x/ecocredit/server/marketplace/query_buy_order.go
- x/ecocredit/server/marketplace/query_buy_order_test.go
- adds single buy order query
ref: #856 
---
I have...
I have...
> feat(marketplace): `QueryBuyOrder` ORM

- x/ecocredit/marketplace/codec.go
- x/ecocredit/marketplace/msg_cancel_sell_order.go
- x/ecocredit/marketplace/msg_cancel_sell_order_test.go
Tests on master are currently failing due to a missing msg implementation for cancel sell order.
---
I have...
I have...
> fix(x/ecocredit): cancel sell order msg

- x/ecocredit/server/marketplace/sell.go
Closes: #XXXX
---
I have...
I have...
> fix(marketplace): add nil check to sell order expiration

- types/timestamp.go
- types/timestamp_test.go
- x/data/server/msg_anchor.go
- x/data/server/msg_attest.go
- x/data/server/utils.go
- x/ecocredit/basket/date_criteria.go
- x/ecocredit/server/basket/put.go
- x/group/server/invariants_test.go
- adds timestamp/duration conversion utility functions
- refactors existing code to use utils instead of directly setting structs
- cleans up test directly setting time.Now() on timestamp instead of using TimestampNow()
Closes: #981 
---
I have...
I have...
> refactor: timestamp utils

- go.mod
- go.sum
- orm/go.mod
- orm/go.sum
- types/go.mod
- types/go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/group/go.mod
- x/group/go.sum
Updating to get https://pkg.go.dev/github.com/stretchr/testify@v1.7.1/assert#ErrorContains
---
I have...
I have...
> chore: bump testify

- x/ecocredit/server/core/create_batch.go
- fixes an issue where the wrong key is used to fetch class 
Closes: n/a
---
I have...
I have...
> fix(ecocredit/core): wrong key type in class lookup

- app/app.go
- x/ecocredit/basket/features/msg_put.feature
- x/ecocredit/basket/features/msg_take.feature
- x/ecocredit/basket/msg_put_test.go
- x/ecocredit/basket/msg_take_test.go
- x/ecocredit/basket/utils.go
- x/ecocredit/server/basket/features/msg_create.feature
- x/ecocredit/server/basket/features/msg_put.feature
- x/ecocredit/server/basket/features/msg_take.feature
- x/ecocredit/server/basket/msg_put_test.go
- x/ecocredit/server/basket/msg_take_test.go
- x/ecocredit/server/testsuite/suite.go
Ref: #895
Followup pull request to #1065, #1098, and #1100 that makes use of a valid basket denom, applies consistent use of "expect" for outcome steps, and simulates token balance results previously mocked without being updated.
---
I have...
I have...
> test(x/ecocredit): clean up basket acceptance tests

- x/ecocredit/server/basket/invariants.go
- x/ecocredit/server/core/query_balances.go
- x/ecocredit/server/core/query_batches_by_class.go
- x/ecocredit/server/core/query_batches_by_issuer.go
- x/ecocredit/server/core/query_class_issuers.go
- x/ecocredit/server/core/query_classes.go
- x/ecocredit/server/core/query_classes_by_admin.go
- x/ecocredit/server/core/query_projects.go
- x/ecocredit/server/core/query_projects_by_reference_id.go
- x/ecocredit/server/core/update_class_test.go
- x/ecocredit/server/marketplace/query_allowed_denoms.go
- adds `defer it.Close()` to iterators that did not already have this.
ref: #715 
---
I have...
I have...
> fix(ecocredit): close iterators

- x/ecocredit/migrations/v3/core.go
ref: #1183 
---
I have...
I have...
> fix(ecocredit): fix escrowed balance & tradable supply migrations

- x/ecocredit/server/basket/invariants.go
- x/ecocredit/server/genesis.go
ref: #1190 
---
I have...
I have...
> fix: fix init genesis to include basket balances

- x/ecocredit/server/core/query_project_info.go
- x/ecocredit/server/core/query_project_info_test.go
- x/ecocredit/server/core/query_projects.go
- x/ecocredit/server/core/query_projects_by_class.go
Closes: #1214 
---
I have...
I have...
> fix(ecocredit): add project reference-id to query response

- .github/workflows/mergify.yml
Updates mergify backport pull request rules to include `release/v3.0.x` and `release/v4.0.x`.
---
I have...
I have...
> ci: add mergify backport pull request rules

- .goreleaser.yml
Update `goreleaser.yml` to publish homebrew taps to a [separate branch](https://github.com/regen-network/regen-ledger/tree/homebrew-taps).
---
I have...
I have...
> ci: publish homebrew taps on separate branch

- x/ecocredit/migrations/v3/patch.go
- x/ecocredit/migrations/v3/patch_test.go
Closes: #1279 
---
I have...
I have...
> feat(x/ecocredit): add issuance date to new credit batches

- CHANGELOG.md
- x/ecocredit/migrations/v3/state.go
- x/ecocredit/migrations/v3/state_test.go
Ref: [1249(comment)](https://github.com/regen-network/regen-ledger/issues/1249#issuecomment-1190071006) 
---
I have...
I have...
> fix(x/ecocredit): add basket state migration

- CHANGELOG.md
- x/ecocredit/server/basket/query_balance.go
- x/ecocredit/server/basket/query_balance_test.go
- x/ecocredit/server/basket/query_balances.go
- x/ecocredit/server/basket/query_balances_test.go
- x/ecocredit/server/basket/query_basket.go
- x/ecocredit/server/basket/query_basket_test.go
- x/ecocredit/server/testsuite/suite.go
Closes: #1275 
---
I have...
I have...
> fix(x/ecocredit): improved error for basket queries

- .github/workflows/build.yml
- go.mod
- go.sum
- types/go.mod
- types/go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/group/go.mod
- x/group/go.sum
This pull request updates all go modules to api/v1.0.0 and removes replace directives.
---
I have...
I have...
> chore: update all go modules to api/v1.0.0

- go.mod
- go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/group/go.mod
- x/group/go.sum
This pull request updates all go modules to types/v1.1.0 and removes replace directives.
---
I have...
I have...
> chore: update all go modules to types/v1.1.0

- go.mod
- go.sum
- x/group/go.mod
- x/group/go.sum
This pull request updates root and x/group go modules to x/ecocredit/v2.0.0 and removes replace directives.
---
I have...
I have...
> chore: update go modules to x/ecocredit/v2.0.0

- go.mod
- go.sum
This pull request updates root go module to x/group/v1.0.0-beta2 and removes replace directive.
---
I have...
I have...
> chore: update root go module to x/group/v1.0.0-beta2

- CHANGELOG.md
Update changelog for official v4.0 release.
---
I have...
I have...
> docs: update changelog for v4.0 release

- docs/.vuepress/config.js
- docs/validators/get-started/README.md
- docs/validators/get-started/create-a-validator.md
- docs/validators/get-started/initialize-node.md
- docs/validators/get-started/install-cosmovisor.md
- docs/validators/get-started/install-regen.md
- docs/validators/get-started/run-a-full-node.md
- docs/validators/get-started/using-cosmovisor.md
- docs/validators/get-started/using-quickstart.md
- docs/validators/get-started/using-state-sync.md
- docs/validators/upgrades/README.md
- docs/validators/upgrades/v2.0-upgrade.md
- docs/validators/upgrades/v3.0-upgrade.md
- docs/validators/upgrades/v4.0-upgrade.md
Closes: #1238
This pull request started out as only adding the v4.0 validator upgrade guide and evolved to include updates to validator getting started and all upgrade guides (including the addition of the v4.0 upgrade guide).
- Added [Upgrade Guide v4.0](https://deploy-preview-1299--regen-ledger-docs.netlify.app/validators/upgrades/v4.0-upgrade.html)
- Update, simplify, and fix [Validator Get Started](https://deploy-preview-1299--regen-ledger-docs.netlify.app/validators/get-started/)
- Update, simplify, and fix [Validator Upgrades](https://deploy-preview-1299--regen-ledger-docs.netlify.app/validators/upgrades/)
---
I have...
*All items are required. …
> docs: add v4.0 validator upgrade guide

- docs/.vuepress/config.js
- docs/README_commands.md
- docs/ledger/README.md
- docs/ledger/get-started/README.md
- docs/ledger/get-started/live-networks.md
- docs/ledger/get-started/local-testnet.md
- docs/ledger/infrastructure/README.md
- x/data/spec/README.md
- x/ecocredit/spec/README.md
Closes: #1307
This pull request updates the documentation to align with the v4.0 release.
---
I have...
I have...
> docs: update documentation to align with v4.0 release

- .github/workflows/sims-nightly.yml
- .github/workflows/test.yml
Closes: #XXXX
---
I have...
I have...
> ci: fix github actions

- docs/validators/get-started/install-regen.md
Update validator install instructions to use latest version for hambach.
---
I have...
I have...
> docs: update hambach install to use latest version

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/docs.md
- .github/PULL_REQUEST_TEMPLATE/other.md
- .github/mergify.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/proto-registry.yml
- .github/workflows/proto.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- README.md
- RELEASE_PROCESS.md
- SECURITY.md
- app/export.go
- app/genesis.go
- docs/ledger/infrastructure/README.md
- docs/ledger/infrastructure/interfaces.md
- docs/tutorials/data-cli.md
- docs/validators/get-started/create-a-validator.md
- docs/validators/get-started/using-state-sync.md
- docs/validators/upgrades/README.md
- make/proto.mk
- x/ecocredit/spec/README.md
Closes: #1260
This pull request updates all references of `master` branch to `main` (including sdk and tendermint links).
---
I have...
I have...
> chore: rename master branch to main

- .github/dependabot.yml
Add dependabot configuration for `gomod` and `npm` packages.
---
I have...
I have...
> ci: add dependabot configuration for gomod and npm

- x/data/server/msg_define_resolver.go
- x/ecocredit/server/basket/msg_create.go
- x/ecocredit/server/core/msg_add_credit_type.go
- x/ecocredit/server/core/msg_create_batch.go
- x/ecocredit/server/core/msg_mint_batch_credits.go
- x/ecocredit/server/marketplace/msg_add_allowed_denom.go
This pull request is a quick fix for failing tests on the main branch (tests which passed CI as a result of not checking gomod and gosum in sub modules - see #1382). Error handling should be improved alongside #1147. This pull request only does the bare minimum to unblock pull requests being merged into master, i.e. the expected error messages are unchanged.
---
I have...
I have...
> fix(x/data,x/ecocredit): update orm error conditions

- .golangci.yml
- types/timestamp.go
- x/data/server/server.go
- x/ecocredit/server/server.go
Removes deprecated linter, fixes lint error in types, and ignores server implementation lint error.
---
I have...
I have...
> style: fix lint errors using latest golanci

- CHANGELOG.md
- go.mod
- go.sum
This pull request updates the changelog and bumps the ecocredit version including support for historical queries.
Changes for historical queries: https://github.com/regen-network/regen-ledger/commit/2c9d9a67bd602c165c007f9075000236288429b9
Manual test for historical queries: https://hackmd.io/4fwlnHNjR7aZEXO_kTx-uA
---
I have...
I have...
> chore: update changelog and bump ecocredit version

- Makefile
- contrib/images/Makefile
- make/sims.mk
Sims Nightly and Tests Nightly are failing due to recent refactoring. This fixes both.
---
I have...
I have...
> ci: fix sims nightly and tests nightly

- app/simulation/app_import_export_test.go
Nightly simulation jobs are failing with following error.
```
panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824648921728}) [recovered]
panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824648921728})
```
---
I have...
I have...
> test(app): fix import-export sim job

- x/ecocredit/marketplace/codec.go
As part of #1483, we need to ensure proposal types are also registered with the LegacyAmino codec. This is done correctly for `CreditTypeProposal` [here](https://github.com/regen-network/regen-ledger/blob/release/v4.1.x/x/ecocredit/core/codec.go#L29), but wasn't done for `AllowDenomProposal`.  This PR fixes that.
---
I have...
I have...
> fix(x/ecocredit): Add amino codec registration for AllowDenomProposal

- x/ecocredit/base/types/v1/codec.go
adds `MsgBridge` to codec registration
Closes: n/a
---
I have...
I have...
> fix: register MsgBridge in codec

- CHANGELOG.md
- x/ecocredit/core/codec.go
Acts as a back port of #1507, but this was implemented manually since we did some folder re-org between v5 and v4.
---
I have...
I have...
> fix: Add amino codec for MsgBridge (release/v4.1.x)

- CHANGELOG.md
- go.mod
- go.sum
We never tagged & bumped a new ecocredit version after #1508, so regen ledger `v4.1.1` didn't actually have the fix in the release.
This PR fixes that.
---
I have...
I have...
> chore(x/ecocredit): bump ecocredit version to v2.3.0

- docs/validators/upgrades/v4.1-upgrade.md
Update `v4.1.2` version in upgrade docs
---
I have...
I have...
> docs: Update v4.1-upgrade.md

- docs/ledger/get-started/live-networks.md
The "Get started -> live networks" page: https://docs.regen.network/ledger/get-started/live-networks.html has two bad links to the validator upgrades overview page. I believe it should link to here: https://docs.regen.network/validators/upgrades/
---
I have...
I have...
> docs: Fix links to validator upgrade overview

- .github/mergify.yml
Updates `mergify.yml` to add config for `backport/v4.1.x` label.
---
I have...
I have...
> chore: add mergify config for backport/v4.1.x label

- specs/rfcs/002-basket-functionality/README.md
Images were not loading when we did some renaming of folders. This fixes the Baskets RFC to render images properly.
Closes: #XXXX
---
I have...
I have...
> docs: fix images on Baskets RFC

- go.mod
- go.sum
Ref: #1456
Add replace directive for confio/ics/go per https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.3
---
I have...
I have...
> build: add replace directive for confio/ics23/go

- x/intertx/go.mod
- x/intertx/go.sum
- x/intertx/keeper/query_interchain_account.go
Closes: #1577 
---
I have...
I have...
> fix(intertx): return grpc error codes in query response

- x/ecocredit/go.mod
- x/ecocredit/go.sum
This pull request bumps the `api` module version in the `ecocredit` module in preparation for v4.1.5 release.
---
I have...
I have...
> build(x/ecocredit): bump api version to v1.1.0

- images/regen-sandbox/bootstrap.sh
It would be convenient to have the REST API available from the `regen-sandbox` node
Closes: #XXXX
---
I have...
I have...
> feat: enable REST API in regen-sandbox

- app/app.go
Closes: #1661
This pull request adds the IBC fee middleware to the IBC transfer module.
---
I have...
I have...
> feat(app): add fee middleware to ibc transfer

- x/ecocredit/server/tests/bridge_test.go
- x/ecocredit/server/tests/features/market.feature
- x/ecocredit/server/tests/market_test.go
- x/ecocredit/server/tests/utils.go
Ref: #1660
This pull request adds marketplace integration tests.
---
I have...
I have...
> test(x/ecocredit): add marketplace integration test

- CHANGELOG.md
- x/ecocredit/marketplace/keeper/query_sell_orders.go
Closes: n/a
---
I have...
I have...
> fix(x/ecocredit): fix sell-orders query index

- app/upgrades/v5_0/upgrade_test.go
- x/ecocredit/base/keeper/msg_send.go
- x/ecocredit/migrations/v3/state.go
- x/ecocredit/migrations/v3/state_test.go
ref: #1660 
Script to get all affected account [link](https://colab.research.google.com/drive/1pZU8HnWFce94BCFWwSUxxaJeEpa3X_QX?usp=sharing).
Also did manual testing with mainnet export.
---
I have...
I have...
> fix(x/ecocredit)!: add batch balance migration

- go.mod
- go.sum
- types/go.mod
- types/go.sum
- x/data/codec.go
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/base/types/v1/codec.go
- x/ecocredit/basket/types/v1/codec.go
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/ecocredit/marketplace/types/v1/codec.go
- x/intertx/go.mod
- x/intertx/go.sum
- x/intertx/types/v1/codec.go
Ref: https://github.com/regen-network/cosmos-sdk/pull/49
This pull request updates to the forked version of v0.46.7 (`v0.46.7-regen-1`), which includes gov and group amino support.
---
I have...
I have...
> build: use sdk v0.46.7-regen and register amino

- app/client/docs/config.json
Closes: #1628
Gov and group swagger endpoints were not registered until cosmos sdk v0.46.7. This pull request updates swagger.
---
I have...
I have...
> docs: update swagger using latest sdk

- x/intertx/client/tx.go
Closes: #1707
Using the same command setup as akash and successfully tested in https://hackmd.io/L4Ru-CeuQZ6VMMrBXYDHLA.
---
I have...
I have...
> fix(x/intertx): use msg json rather than tx json

- .goreleaser.yml
Since #1698 hasn't been fully resolved, this PR temporarily removes darwin amd64 builds from goreleaser ( as well as homebrew setup - which was also failing), which should get the goreleaser action to pass again.
Tested locally with:
- updating "args" section of goreleaser step in release.yml from `release --rm-dist` to `build --skip-validate --skip-before --rm-dist`
- running `act -j release --container-architecture linux/amd64 -v`
---
I have...
I have...
> build: remove darwin amd64 builds from goreleaser

- scripts/githooks/commit-msg
Closes: #1482
This pull request updates the semantic commit regex to support scope and previously missing types.
---
I have...
I have...
> chore: fix githook semantic commit check

- go.mod
- go.sum
- types/go.mod
- types/go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/intertx/go.mod
- x/intertx/go.sum
Ref: https://github.com/regen-network/cosmos-sdk/pull/51
This pull request updates the sdk version to the latest fork version that includes gov migration fixes.
Manual Testing: https://hackmd.io/dQLSDStnSMGEnxp-ahXlvg
---
I have...
I have...
> build: update sdk version to updated fork version

- go.mod
- go.sum
- types/go.mod
- types/go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/intertx/go.mod
This pull request removes the replace directive to use the official `api/v2.0.0` release tag.
---
I have...
I have...
> build: update api version in all modules

- go.mod
- go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/intertx/go.mod
- x/intertx/go.sum
This pull request removes the replace directive to use the official `types/v2.0.0` release tag.
---
I have...
I have...
> build: update types version in all modules

- go.mod
- go.sum
This pull request removes replace directives to use the official module release tags.
---
I have...
I have...
> build: update module versions in app module

- CHANGELOG.md
This pull request updates the changelog in preparation for the v5.0.0 release.
---
I have...
I have...
> docs: update changelog for v5.0.0 release

- docs/.vuepress/config.js
- docs/validators/upgrades/v5.0-upgrade.md
This pull request adds the v5.0 upgrade guide link to the sidebar and updates the block heights.
https://www.mintscan.io/regen/blocks/8942600
https://github.com/regen-network/governance/pull/16
Starting Block: 7,117,583 (http://redwood.regen.network:1317/blocks/7117583)
Starting Block Time: January 5th 2022 08:00:03 AM
Average Block Time: 5.593s (https://redwood.regen.aneka.io/)
Seconds in a day: 86,400s
86400 / 5.593 = 15447.8812802 blocks per day
15447.8812802 x 4 = 61791.5251207 blocks for 4 days
7117583 + 61791.5251207 = 7179374.52512 block height
Upgrade Height: 7179375
---
I have...
*All items are required. Please add a note if the item is not …
> docs: add v5.0 upgrade link and heights

- docs/validators/upgrades/v5.0-upgrade.md
This pull request fixes the v5.0 upgrade binary directory in the upgrade guide. Also noticing that the go version needs to be updated but is correct in `main` and `release/v5.0.x` - will resolve in the backport pr.
---
I have...
I have...
> docs: fix v5.0 upgrade binary directory

- types/go.mod
- types/go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
This pull request bumps the `api` module version to `v2.1.0` in `types`, `x/data`, and `x/ecocredit` (not imported in `x/intertx` and imported indirectly via `types` in the root level app).
---
I have...
I have...
> build: bump api module version

- .github/mergify.yml
This pull request adds mergify backport for the new `release/v5.1.x` branch.
---
I have...
I have...
> ci: add backport for v5.1.x release branch

- CHANGELOG.md
This pull request adds three relevant changes to the changelog for `v5.1`.
---
I have...
I have...
> chore: add missing items to changelog

- go.mod
- go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/intertx/go.mod
- x/intertx/go.sum
Ref: #1855
This pull request bumps the `types` module version to `v2.3.0` in `x/data`, `x/ecocredit`, `x/intertx`, and root app. 
---
I have...
I have...
> build: bump types module version

- CHANGELOG.md
Closes: #1855
This pull request updates the release date in the changelog.
---
I have...
I have...
> docs: update release date in changelog

- docs/.vuepress/config.js
- docs/validators/upgrades/v2.0-upgrade.md
- docs/validators/upgrades/v3.0-upgrade.md
- docs/validators/upgrades/v4.0-upgrade.md
- docs/validators/upgrades/v4.1-upgrade.md
- docs/validators/upgrades/v5.1-upgrade.md
Ref: #1855
This pull request adds a validator upgrade guide for `v5.1`.
Calculations: https://hackmd.io/KYpw8B01RUaeO-WsjE27tA
---
I have...
I have...
> docs: add v5.1 validator upgrade guide

- docs/.vuepress/config.js
- docs/ledger/migrations/README.md
- docs/ledger/migrations/v5.1-migration.md
- x/ecocredit/spec/01_concepts.md
- x/ecocredit/spec/02_state.md
- x/ecocredit/spec/03_messages.md
- x/ecocredit/spec/04_queries.md
- x/ecocredit/spec/05_events.md
- x/ecocredit/spec/06_types.md
Ref: #1855
This pull request adds a developer migration guide for `v5.1`.
---
I have...
I have...
> docs: add v5.1 developer migration guide

- docs/ledger/migrations/v5.1-migration.md
- docs/validators/upgrades/v2.0-upgrade.md
- docs/validators/upgrades/v3.0-upgrade.md
- docs/validators/upgrades/v4.0-upgrade.md
- docs/validators/upgrades/v4.1-upgrade.md
- docs/validators/upgrades/v5.0-upgrade.md
- docs/validators/upgrades/v5.1-upgrade.md
This pull request fixes `git fetch` in the validator upgrade guide and a link in the developer migration guide.
---
I have...
I have...
> docs: fix upgrade and migration guide

- CHANGELOG.md
- go.mod
- go.sum
This pull request adds the changleog entry for `v5.1.1` and bumps to the latest patch release for `x/intertx`.
---
I have...
I have...
> chore: v5.1.1 release prep

- docs/validators/upgrades/v5.1-upgrade.md
This pull request bumps the version from `v5.1.0` to `v5.1.1` in the upgrade guide. Release notes still link to `v5.1.0` release with information about the `v5.1` release.
---
I have...
I have...
> docs: bump version in v5.1 upgrade guide

- docs/ledger/README.md
- docs/ledger/get-started/live-networks.md
This pull request updates block explorers and faucets in the documentation.
---
I have...
I have...
> docs: update faucet info

- go.mod
- go.sum
- x/data/go.mod
- x/data/go.sum
- x/ecocredit/go.mod
- x/ecocredit/go.sum
- x/intertx/go.mod
- x/intertx/go.sum
This pull request bumps `types` to the latest version in preparation for `v5.1.2`.
---
I have...
I have...
> build: update all modules to types v2.3.1

- docs/ledger/get-started/local-testnet.md
docs: add update for min-gas-prices in local-testnet tutorial
---
I have...
I have...
> docs: add update for min-gas-prices in local-testnet tutorial

- docs/tutorials/user/credit-class-project-batch-management.md
This pull request adds a note to the credit class, project, and batch tutorial about using a json-ld filepath.
---
I have...
I have...
> docs: add note about json-ld filepath

- LICENSE
- docs/README.md
This pull request updates the company title of Regen Network Development from Inc to PBC.
---
I have...
I have...
> docs: update company title from inc to pbc

- docs/.vuepress/config.ts
- docs/package.json
- docs/yarn.lock
Closes: #2065 
---
I have...
I have...
> feat(docs): add sitemap

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> chore: Update changelog for v5.1.3

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> docs: Update CHANGELOG.md for v5.1.4

- .github/mergify.yml
Closes: #XXXX
---
I have...
I have...
> ci: add mergify rules for release v.6.0.x

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> chore: create branch for release V6.0.x and updated changelog

- x/data/spec/07_client.md
fix some comments
---
I have...
I have...
> chore: fix some comments

- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile
- make/release.mk
Closes: #XXXX
---
I have...
I have...
> chore: temproarly docker based build for regen

- .github/workflows/tests.yml
- app/app.go
- app/client/cli/cmd_test.go
- app/client/cli/root.go
- app/client/cli/testnet.go
- app/simulation/app_after_import_test.go
- app/simulation/app_determinism_test.go
- app/simulation/app_import_export_test.go
- app/simulation/app_test.go
- app/simulation/utils.go
- app/testsuite/app_test.go
- app/testsuite/helpers.go
- app/testsuite/network_config.go
- app/testsuite/suite.go
- app/upgrades/v5_0/upgrade.go
- app/upgrades/v5_0/upgrade_test.go
- app/upgrades/v5_1/upgrade.go
- app/upgrades/v6_0/upgrade.go
- app/upgrades/v6_0/upgrade_test.go
- cmd/regen/main.go
- go.mod
- scripts/generate_cli_docs.go
Closes: #XXXX
---
I have...
I have...
> feat: add v6 upgrade handler

- make/release.mk
Closes: #XXXX
---
I have...
I have...
> chore: fix make release command

- docs/.vuepress/config.ts
Closes: #XXXX
---
I have...
I have...
> docs: add missing migration guide v6 in menu
