app/app.go
go.mod
go.sum

Adds an upgrade handler for the `amazonas` upgrade and upgrades the Cosmos SDK fork to the latest regen-network/upgrade-module-v0.4 branch

Amazonas upgrade

---

README.md
docs/getting-started.md
go.mod

Cosmos SDK min go version is 1.15. We shouldn't use lower version.

Bump min go version to 1.15

---

x/ecocredit/server/msg_server.go

Correctly populate BatchInfo metadata

---

Makefile

The PR fixes `regen version` and `regen version --long` commands to show proper release version

Fix version issue

---

app/app.go
app/app_test.go
app/regen/cmd/root.go
app/sim_test.go
app/test_helpers.go
testutil/network/network.go

`--x-crisis-skip-assert-invariants` integration in `app.go` might had missed while upgrading the code to stargate, this PR adds it.

use `--x-crisis-skip-assert-invariants` flag in app

---

.github/ISSUE_TEMPLATE/module_readiness_checklist.md

Basic template from @aaronc's suggestions in #253 
Some ideas of things that may be missing from here:
- do we need to audit anything about intermodule wiring in cases where that happens?
- I added a note about documentation (godoc + readme.md). We currently don't have the same docs structure as in the cosmos-sdk (where module directories have .md files with docs that get copied to their vuepress). What is our general documentation expectation for high level docs about things like functionlaity, store usage, API surface, events, etc.?
- Where in this checklist do we check for correct signature verifications? (e.g. that GetSIgners() is setup correctly for all Msg's), anything else abt authentication that we should add in this checklist?
- Do we need to add any base level x/upgrade support …

Add module readiness checklist issue template

---

app/experimental_appconfig.go
go.mod
go.sum

For our second prelaunch chain (to be launched Fri April 9), we would like to update the following dependencies on regen ledger:
- update our SDK fork to an updated version of the SDK based off of v0.42.4 (**BLOCKED** on https://github.com/regen-network/cosmos-sdk/pull/41)
- update wasmd to v0.15. Even though this is not live in our mainnet build, it is recommended to upgrade as v0.15 fixes some bugs from v0.14 (recommended by @ethanfrey)

build: update to final dependencies for v1.0.0-rc3

---

app/addr_prefixes.go

Came up during PR review on SDK [ref](https://github.com/cosmos/cosmos-sdk/blob/master/types/address.go#L28-L34).

fix: parse key freezes

---

x/ecocredit/server/msg_server.go

Add fixed gas cost to ecocredit messages per-loop-iteration
Closes: #519 
---
I have...
I have...

feat: Add gas per-loop-iteration in ecocredit messages (#519)

---

x/ecocredit/client/testsuite/query.go
x/ecocredit/client/testsuite/tx.go
x/ecocredit/denom.go
x/ecocredit/msgs.go
x/ecocredit/msgs_test.go
x/ecocredit/server/testsuite/queries.go

Closes: #551 
---
I have...
I have...

feat: add `ValidateDenom` for `MsgSend`, `MsgRetire`, and `MsgCancel`

---

proto/regen/ecocredit/basket/v1beta1/state.proto
proto/regen/ecocredit/marketplace/v1beta1/state.proto
proto/regen/ecocredit/v1beta1/state.proto

This resolves issues with proto lint introduced in #700. It also renames the `ProjectSequence.project_id` field to `class_id` - an issue that was identified in most merge review.
---
I have...
I have...

fix: proto lint

---

x/ecocredit/client/basket/query.go
x/ecocredit/client/query.go

Closes: #XXXX
---
I have...
I have...

feat: add basket balance queries

---

types/go.mod
types/math/dec.go
types/math/dec_test.go
x/ecocredit/server/basket/put.go

Addresses (well-founded) concerns about missing decimal tests in audits, and dec -> int conversion issue uncovered in #769 
---
I have...
I have...

feat(types): better tests for math and correct decimal -> integer conversion in x/ecocredit

---

CHANGELOG.md
RELEASE_NOTES.md

Adds release notes for `v3.0.0`.
---
I have...
I have...

docs: v3.0.0 release notes

---

.github/workflows/lint.yml
app/app.go
app/stable_appconfig.go
x/ecocredit/module/module.go

fix: ecocredit module migration

---

go.mod
orm/primary_key_property_test.go
x/ecocredit/server/marketplace/query_sell_orders_test.go

Closes: #1068
This pull request fixes `TestSellOrders` and disables `TestPrimaryKeyTable`, both of which were causing intermittent errors, and the second being part of the orm module, which is no longer maintained and will soon be deleted.
---
I have...
I have...

test: fix ecocredit test and disable orm test

---

x/ecocredit/server/basket/msg_create.go
x/ecocredit/server/basket/msg_create_test.go

Ref: [#1190(comment)](https://github.com/regen-network/regen-ledger/issues/1190#issuecomment-1157787842)
---
I have...
I have...

fix(basket)!: store basket denom units in ascending order

---

x/ecocredit/client/testsuite/suite.go
x/ecocredit/client/testsuite/tx_marketplace.go
x/ecocredit/server/marketplace/features/msg_buy_direct.feature
x/ecocredit/server/marketplace/msg_buy_direct.go
x/ecocredit/server/marketplace/msg_buy_direct_test.go

Closes: #1216
This pull request adds a check and tests to make sure the buyer is not the seller when processing a buy order.
---
I have...
I have...

feat(x/ecocredit): buyer cannot be the same as seller

---

CHANGELOG.md
x/ecocredit/server/core/features/msg_create_batch.feature
x/ecocredit/server/core/msg_create_batch.go
x/ecocredit/server/core/msg_create_batch_test.go

- fixes a bug where the `open` field was not used from the request in `CreateBatch`
- updates test to include the `open` property set to `true`
Closes: n/a
---
I have...
I have...

fix(ecocredit): use `open` field when creating batch

---

CHANGELOG.md
x/ecocredit/migrations/v3/patch.go
x/ecocredit/migrations/v3/patch_test.go

Closes: #1280 
---
I have...
I have...

fix(x/ecocredit): basket curator migration

---

CHANGELOG.md
x/ecocredit/client/basket/query.go
x/ecocredit/client/basket/tx.go
x/ecocredit/client/marketplace/query.go
x/ecocredit/client/marketplace/tx.go
x/ecocredit/client/query.go
x/ecocredit/client/testsuite/query.go
x/ecocredit/client/testsuite/suite.go
x/ecocredit/client/testsuite/tx_basket.go
x/ecocredit/client/testsuite/tx_marketplace.go
x/ecocredit/client/tx.go
x/ecocredit/server/core/keeper_test.go
x/ecocredit/server/core/query_balances_test.go
x/ecocredit/server/core/query_batches_by_class_test.go
x/ecocredit/server/core/query_batches_by_issuer_test.go
x/ecocredit/server/marketplace/query_sell_orders_test.go

Closes: #1271
---
I have...
I have...

refactor(x/ecocredit): clean up commands and examples

---

x/ecocredit/client/testsuite/suite.go
x/ecocredit/core/default.go
x/ecocredit/core/params.go
x/ecocredit/core/types_batch.go
x/ecocredit/core/types_class.go
x/ecocredit/core/types_class_issuer.go
x/ecocredit/core/types_project.go
x/ecocredit/genesis/genesis.go
x/ecocredit/genesis/genesis_test.go
x/ecocredit/marketplace/default.go
x/ecocredit/module/module.go
x/ecocredit/server/genesis.go
x/ecocredit/server/testsuite/suite.go
x/ecocredit/simulation/genesis.go

Closes: #1158
This pull request updates default genesis values to include a default credit type and a default allowed denom to make it easier for starting a local testnet and then testing against that local testnet.
In order to support a default allowed denom (a marketplace type), a separate `genesis` package was created in the root of the module directory (previously in `core` - was probably not the right place anyways). Import cycles were violated in `module` and in the root of the ecocredit module so a separate `genesis` package was the simplest solution.
Validation functions for class, class issuers, project, and batch were moved to respective type files for each within `core`.
Manual tests: https://hackmd.io/WYHeLuIQSKOnLlJVGsFVnw (including upgrade tests just to be sure this does …

feat(x/ecocredit): default values for new ORM params

---

docs/.vuepress/config.js
docs/validators/upgrades/README.md
docs/validators/upgrades/v4.1-upgrade.md

Closes: #XXXX
---
I have...
I have...

docs: added 4.1 upgrade doc

---

types/math/dec.go
types/math/dec_test.go

Closes: #1493 
---
I have...
I have...

fix(types):  dec from string must be finite

---

docs/ledger/get-started/README.md

Closes: #XXXX
In the Linux section, the last step to run 'regen version' doesn't seem to require opening a new terminal. I was able to do this in the same session. This is a small change but I thought it would just make it a little be clearer.
---
I have...
I have...

docs: opening a new terminal isn't necessary

---

x/ecocredit/marketplace/keeper/features/msg_buy_direct.feature
x/ecocredit/marketplace/keeper/msg_buy_direct.go
x/ecocredit/marketplace/keeper/msg_buy_direct_test.go
x/ecocredit/marketplace/keeper/utils.go

Ref: #1660
While auditing buy direct, I noticed we are missing a transfer event. This pull request adds the missing transfer event and also improves comments for the fill order logic used when purchasing credits.
---
I have...
I have...

fix(x/ecocredit): add missing transfer event

---

app/app.go
x/intertx/client/query.go
x/intertx/client/tx.go

Closes: #1700
Fix intertx keeper initialization out of order introduced in #1664.
Manual Testing: https://hackmd.io/imNT6v-zTmWMs629ml9QxQ
---
I have...
I have...

fix(app): intertx not using initialized controller

---

go.mod
go.sum
scripts/release-setup.sh
types/go.mod
types/go.sum
x/data/go.mod
x/data/go.sum
x/ecocredit/go.mod
x/ecocredit/go.sum
x/intertx/go.mod
x/intertx/go.sum

Ref: #1698 
I was finally able to get the issue in #1698 reproducing locally (running https://github.com/nektos/act again).
Unfortunately, just running `act` on its own wouldn't quite work properly. Running the `goreleaser` action requires GitHub Tokens and will push binaries to GitHub release's API, etc.
Instead I ran:
- `act -j release --container-architecture linux/amd64 -v`
- when the process failed (due to missing GitHub tokens), I shelled into the docker container with: `docker exec -it ${container_id} /bin/bash`
- ran `ln -s /opt/hostedtoolcache/go/1.19.4/x64/bin/go /usr/bin/go` to add the go binary in my PATH
- ran ` /opt/hostedtoolcache/goreleaser-action/1.13.1/x64/goreleaser build --skip-before  --skip-validate --help -id regen-darwin-amd64` to build the failing darwin binary …

build: update 99designs/keyring to use cosmos fork

---

docs/ledger/README.md
docs/ledger/get-started/README.md
docs/ledger/get-started/live-networks.md
docs/validators/get-started/initialize-node.md
docs/validators/get-started/install-regen.md

Closes: #1770
This PR removes any references to Hambach testnet.
---
I have...
I have...

docs: remove references to hambach testnet

---

app/client/cli/cmd_test.go

When we updated to go 1.19, we received deprecation errors that required updating `io/ioutil` to `os`. The use of temporary directory was not properly set up for one of the tests and therefore the test fails with the error `genesis.json already exists` when tests are run more than once locally. This pull request fixes the issue.
---
I have...
I have...

test: fix cmd test temp directory

---

x/ecocredit/migrations/v4/state.go

New metadata added:
[C01-001-20150101-20151231-001](https://api.registry.regen.network/metadata-graph/regen:13toVg38ZRvFxPA2TBNnxGhabgogpJnv4LDm7YPgSuzuETiXz8GbnTF.rdf)
[C01-001-20150101-20151231-002](https://api.registry.regen.network/metadata-graph/regen:13toVhTFtGtXxoHw7yy3QQVDGEpSQoVy4VARhtTWeuNQa5V25WUhagq.rdf)
[C01-001-20150101-20151231-003](https://api.registry.regen.network/metadata-graph/regen:13toVghYySmmX9gm76MuwiPCC9AJy6Psb7wj6uj9JiBk4NvACGkpJDw.rdf)
[C01-001-20150101-20151231-004](https://api.registry.regen.network/metadata-graph/regen:13toVgGhCxGuNrqKKugLY9thKAdLTgXHGxhbVutz2QLgtFmdZzPAKUB.rdf)
[C01-001-20150101-20151231-005](https://api.registry.regen.network/metadata-graph/regen:13toVhaDUK1CHmqdZfKr6ZdF1L1ekTvUgjbEiGxWYqDWVZ937GUviFr.rdf) …

chore: add batches new metadata

---

app/app.go

Upgrade IBC client proposal is failing with error 
```
Error: no concrete type registered for type URL /ibc.core.client.v1.ClientUpdateProposal against interface *types.Msg
```
---
I have...
I have...

fix: register ibc client update proposal handlers

---

docs/tutorials/user/credit-class-project-batch-management.md

Adds a note to the credit class management tutorial about the credit type that's likely to be used when following the tutorial.
---
I have...
I have...

docs: add note about credit type to credit class tutorial

---

app/client/cli/root.go

SDK 0.45 and 0.46 made a pruning subcommand available: https://github.com/cosmos/cosmos-sdk/pull/12742 and https://github.com/cosmos/cosmos-sdk/issues/12727
This command allows you to prune old states on-demand & offline. This is useful because old states are not automatically pruned when you change pruning settings.
I've included the pruning command in the `regen` root command using this PR as an example: https://github.com/provenance-io/provenance/pull/1209
---
I have...
I have...

feat: add pruning subcommand

---

go.mod
go.sum

Fixes bug where latest Ledger Firmware + Ledger Cosmos App is incompatible with Regen Ledger.
More info: https://github.com/cosmos/cosmos-sdk/issues/18319
---
I have...
I have...

chore: version bump for ledger-cosmos-go

---

CHANGELOG.md
go.mod
go.sum
x/data/client/irigen.go
x/data/client/query.go
x/data/client/testsuite/query.go
x/data/go.mod
x/data/go.sum
x/data/iri.go

Closes: #XXXX
Testing instructions:
* try `generate-iri` with a `.jsonld` file
* try `generate-iri` with another non RDF file
* try `convert-iri-to-hash` with some IRI
* try `convert-hash-to-iri` with some hash
---
I have...
I have...

feat(x/data/v2/client)!: add generate-iri command

---

app/client/cli/cmd_test.go
app/simulation/app_after_import_test.go
app/simulation/app_determinism_test.go
app/simulation/app_import_export_test.go
app/simulation/app_test.go
app/testsuite/app_test.go
app/testsuite/modules_test.go
scripts/generate_cli_docs.go
scripts/start_dev.sh
x/data/server/testsuite/suite_test.go
x/ecocredit/base/simulation/msg_add_class_creator.go
x/ecocredit/base/simulation/msg_add_credit_type.go
x/ecocredit/base/simulation/msg_remove_class_creator.go
x/ecocredit/base/simulation/msg_set_class_creator_allowlist.go
x/ecocredit/base/simulation/msg_update_class_fee.go
x/ecocredit/basket/simulation/msg_update_basket_fees.go
x/ecocredit/marketplace/keeper/msg_buy_direct_test.go
x/ecocredit/marketplace/simulation/msg_add_allowed_denom.go
x/ecocredit/marketplace/simulation/msg_remove_allowed_denom.go
x/ecocredit/server/server_test.go
x/ecocredit/server/tests/utils.go

Closes: #XXXX
---
I have...
I have...

chore: upgrade tests
